Feature/add access control
elixir-cloud-aai/foca pull request #109
Opened 2021-11-01 04:34 UTC by kushagra189

## Description
Implement the access-control under FOCA specification.

Fixes #107 

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist:

- [] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not reduced the existing code coverage

2021-12-14 05:26 UTC, uniqueg requested changes
After all, there are quite a lot of comments. Most of them are very simple to fix, but some need some re-design.

The most critical issues:
- The permission/rule model in the spec still needs some work - see the individual comments. Currently I am not able to follow how permissions are really constructed based on these `v0` through `v5` properties. At the very least this will need much better documentation, but possibly also some redesign. It's probably best to start with this. Please describe in some detail how this currently works, why you have implemented it with this `v0` to `v5` pattern and then we can see how we can improve on that.
- The new controllers need handling of `401` (should be handled automatically if `auth` is `required` and security definitions are added in the access control `SpecConfig`) and `403` (implement in the controllers themselves), and the default policy file has to attach all permissions to a single admin user who can then manage permissions via the API (this needs to be configured and implemented somehow still, I think).
- I think we should use the already existing mechanisms in FOCA to set up the access control database and API endpoint registration via a config file. This will make the main module a lot easier and leave just the Casbin enforcer registration in there. I think what we could, for example, have the following behavior: we remove the `enable` property and configure access control whenever the user provides at least the `access_control:` stub. Inside the `AccessControlConfig` model we could provide two additional properties `use_default_db_config` and `use_default_api_specs`. For each of these, when set to `True` (default), the config files are read from a file `config_defaults_access_control.yaml` inside the FOCA repo where the necessary default `db.dbs` and `api.spec` config params are listed, and appended to the app config provided by the user. If set to `False`, users are responsible for providing suitable `db.dbs` and `api.specs` entries in the app config themselves. The `AccessControlConfig` should also include the `db_name` and `collection_name` properties, which, by default, should match the default access control database configuration in `config_defaults_access_control.yaml`. Other properties in the `AccessControlConfig` can remain as they are. In this way, the minimum that's needed from a user to enable access control with the default configuration is just the `access_control:` stub without any params passed to any of the properties (as they all have defaults). If they _don't_ want access control, they can just omit the `access_control:` section altogether. In this way, we only need a single function to register Casbin, the policy file, and a file containing the default specs. The config handler has to be changed to accommodate the merging behavior if the default access control config is to be used, including the check for database/collection name consistency between what is provided as db and collection names in the `AccessControlConfig` and the databases/collections that are to be registered with MongoDO _and_ ensuring that no two collections of the same name are to be registered in the same database (it should be fine to have the same collection name in different databases and different collections in the same database though). This latter check should be applied across all listed database/collection pairs, not just between the ones for access control and the ones provided by the user. Also, this will probably need to be done prior to merging to ensure that a user entry is not overridden by merging or vice versa. Again, all these changes need to be done in the config parser, in the most generic way possible.
- Make sure that the petstore test really works with the behavior described in the points above, including the admin user. This will likely require not only `access_control` to be enabled but also `auth.require` to be set to `True` as we will need to have a user identity passed to the endpoints, or not? But it's a good idea anyway to have a petstore example with authorization configured for all endpoints. However, I would recommend to have a second petstore example `petstore_access_control` for this case, leaving the current one as it is (or was before this PR).
- Finally, I think it's time to set the default for `auth.require` to `True` in https://github.com/elixir-cloud-aai/foca/blob/fb2cd6573f346125be6b1c312a6c344c87b87614/foca/models/config.py#L705 - we don't want to encourage people to develop unprotected APIs! Speaking of this, it seems that we forgot to document the `require` property in that model, in the `Args:`, the `Attributes:` and the `Example:` sections: https://github.com/elixir-cloud-aai/foca/blob/fb2cd6573f346125be6b1c312a6c344c87b87614/foca/models/config.py#L650-L698, also see here: https://foca.readthedocs.io/en/latest/modules/foca.models.html#foca.models.config.AuthConfig. Let's use the opportunity and add that.

I think it shouldn't be as much as it sounds. I suppose the biggest work was to understand casbin and get to a first implementation, and for that it's pretty good. Quite a bit of the suggestions are basically just refactoring. But given that we want to have a good version before we move to Anurag and that this affects the behavior of FOCA deeply, and currently in (too) many modules, I think it's quite important that we implement this as clean as possible in the first round. I don't think this PR is too far awat from that :)

2021-12-14 05:26 UTC, uniqueg commented on examples/petstore/docker-compose.yaml
> +    image: foca-petstore-root:latest
To make it more clear what is happening here, perhaps add a comment to say that this is a workaround to get that image built based on the current state of the repo and that after the image is built the container is started but immediately stops. You could also add an explicit `restart: no` (it's the default, but it's easier to understand/follow if stated explicitly)

2021-12-14 05:26 UTC, uniqueg commented on examples/petstore/config.yaml
> +access:
I think `access` and `enable` is misleading, because access is actually the least restricted if `enable` is `false`, which is counter-intuitive. I would probably prefer to have `access` renamed to `access_control`.

2021-12-14 05:26 UTC, uniqueg commented on examples/petstore/petstore_policies.conf
> +# Request definition
Given that this is an example it would be good to add comments that explain in more detail what is happening here in each line, with a link to more information on Casbin/PyCasbin

2021-12-14 05:26 UTC, uniqueg commented on foca/database/register_mongodb.py
> -
I think it's better not to change more files than necessary in each PR, especially if they are rather big ones, and so given that the line removal here is the only change and has no functional consequences, I would put that line back in again

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +from foca.permission_management.config_utils import _create_permission_config, _register_permission_specs, _register_casbin_enforcer
It's best practice to put multiple imports in parentheses, and if the lines becomes long, to put individual imports on different lines, e.g.,:

```
from foca.permission_management.config_utils import (
    _create_permission_config.
    _register_permission_specs,
    _register_casbin_enforcer,
)

etc. Similarly for the next line.

Also, there is a Python convention that methods/function whose names start with an underscore are to be considered private (they aren't _really_ private, because there is no such thing in Python). So if you have functions that you are going to import elsewhere in your code (except within your test cases), you probably shouldn't have their names start with a `_`.

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +from foca.permission_management.config_utils import _create_permission_config, _register_permission_specs, _register_casbin_enforcer
I'm also thinking that in order to stay consistent with the corresponding section in the app config, it might be better to rename the module `access_control` rather than `permission_management`. It's also 50% shorter...

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +class AccessConfig(FOCABaseConfig):
As mentioned above, better `AccessControlConfig`

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +    #TODO: add check for a valid conf file
Please add issues for these and remove the `TODO`s from the code

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +    # resolve relative path
Is there something missing? If yes, please implement, if not, please remove comment/stub

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +    access: Optional[AccessConfig] = None
Please update docstring (`Args`, `Attributes` and `Example`). Please update examples also in dependent models, if any (probably there aren't any though).

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +        path_out: Policy file based on `pycasbin` specification.
Might be good to add a link here and in the corresponding attribute, something like, `Cf. https://github.com/casbin/pycasbin`

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +
Please also add/describe `owner_headers` and `user_headers` if you use them in your code. If you are _not_ making use of them in your code, please remove them from the model.

2021-12-14 05:26 UTC, uniqueg commented on foca/models/config.py
> +    owner_headers: Optional[set] = {'X-User', 'X-Group'}
Wouldn't it be better to set the defaults to `None` if you allow these to be optional?

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +    if conf.access and conf.access.enable:
Would be better to be more explicit about `if conf.access`: the property `.access` should always be there in a config instance, but it _may_ be `None` - which is what you are checking here. It's not good practice to use `None` in boolean context: https://stackoverflow.com/questions/7816363/if-a-vs-if-a-is-not-none

So better/safer to say: `if conf.access is not None and conf.access.enable:` here...

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +    conf = _create_permission_config(conf)
Do you need to do this if `conf.access.enable` is `False`? Also, please add logging.

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +
Add comment describing what you are doing

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +    else:
Probably enough to log once for the `else` case, something like `No access control configured.`

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +    # Register permission management and casbin enforcer
Couldn't the previous block from lines 68 to 72 maybe be moved down here so that we don't have three code blocks dealing with access control/permission management?

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/constants.py
> +PERMISSION_DB_NAME="access_db"
I know I said that these don't need to be configurable in the first implementation. Nevertheless I feel that they should be added to the config as everything will be in one place, there's less specific documentation to be written and one module less to maintain. If it's a hassle to make this configurable at the moment, you can just define them as attributes and not arguments and then hardcode these as defaults. However, if it's not a lot more work, you might as well make them configurable now.

In any case, we probably need to make a check somewhere that collection names within a database are not repeated. But that can go in a different PR (can create an issue)

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +from foca.permission_management.constants import PERMISSION_DB_NAME, PERMISSION_DB_COLLECTION_NAME
See the comment in the `constants` module about these

2021-12-14 05:26 UTC, uniqueg commented on foca/foca.py
> +            db_port=conf.db.port
I feel that this function has quite a messy API. At this time, all of these are available inside the `cnx_app` object (or, in the case of `PERMISSION_DB_NAME` and `PERMISSION_DB_COLLECTION_NAME` _should be_ in there, see other comments above and below in the `constants` module).

One thing about this though: I'm afraid in our current implementation of `register_mongodb()`, we have side effects, because we are basically just saying that we can pass a Connexion app object - but if people just do that without first attaching the config (including the right attributes/keys), they will get all kinds of `AttributeError`s.

So probably the best is to pass the minimum amount of config models (that's basically why we have them!) to the functions, but _not_ attributes individually. As a rule of thumb, I would apply the rule of threes here, i.e., if we need to pass three or more submodels to a function to pass all the attributes we are going to need in it, we should pass the next higher up submodel, all the way up to passing the entire `Config` model, if necessary. In this way, our functions' APIs and our main module here won't get too messy and we still have all the benefits of having explicit requirements with the possibility to check types. 

I would suggest to start implementing this pattern here (then later change it in `register_mongodb()` and other places, if there are more, please open an issue). So for registering the Casbin enforcer, the function signature would become something like this:

```
register_casbin_enforcer(
    app: App,
    ac_config: AccessControlConfig,
    db_config: MongoConfig,
) -> App:
```

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/constants.py
> +"""File to store permission based constants
Short docstrings <81 chars should go on one line as per PEP 8. Also, our docstrings end with a full stop. Anyway, we probably won't need this module, see comment below.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +"""Methods to manage permission management configuration"""
I would put this in `foca.access_control.register_casbin` to keep consistency with how we do it for `foca.database.register_mongodb`

2021-12-14 05:26 UTC, uniqueg commented on requirements.txt
> +flask-authz==2.4.0
Please sort dependencies alphabetically

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  title: 'FOCA permission control API specification'
Better to use vocabulary consistently. Either `access control` or `permission management`. I'd favor the first one because it is shorter and is consistent with abbreviations like ABAC and RBAC.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  description: 'CRUD and List Operations for managing permission.'
managing permissions (plural)

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +    url: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/LICENSE'
Please link to the permissions in the FOCA repo instead

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +    name: 'GA4GH Discovery Networks Team'
Please use `ELIXIR Cloud & AAI` with the contact `alexander.kanitz@alumni.ethz.ch` (we really need a service email....)

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  - url: /admin/permission-management
better: `/admin/access-control`

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        sec:
Better be explicit so that the specs will document themselves as best as possible.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        ptype:
Better: `policy_type`

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Policy type.
What are the options here?

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Unique id of the permission.
Better: "identifier" instead of "id"

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Section name.
Not obvious what `p` and `g` are. If possible, use explicit values here. Otherwise mention what the abbreviations stand for in the description.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Param 5.
This is very opaque. Isn't there a better way to do this? If you want to allow users to provide an arbitrary set of keys and values, you can use `additionalProperties` like so:

```
Rule:
  description: Rule definition.
  type: object
  additionalProperties:
    type: string
```

See here for more details: https://swagger.io/docs/specification/data-models/dictionaries/

If you really really need these five properties, and each of them has a specific meaning, then it's best to give them descriptive names and extend the descriptions.

If you don't need to call the properties by name, then you should use a list of strings instead.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  schemas:
All the schemas should include reasonable examples: https://swagger.io/docs/specification/adding-examples/

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        '404':
Should contain `401` and `500` as well, and `404` should be listed _after_ `403`.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +                  $ref: '#/components/schemas/Permission'
Add errors responses: `400`, `401`, `403` and `500`

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +      parameters:
This will not be enough to allow pagination, but I think for now that's fine (but please open an issue).

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        '400':
`400` responses in `GET` and `DELETE` endpoints where only path parameters are defined and adding arbitrary query parameters is not forbidden probably cannot arise (I'm not sure). I'm fine with removing them in these cases, but I'm also fine with keeping them in the specs just in case (they won't hurt). However, let's try to be consistent, so please either add them for both the `GET` and `DELETE` endpoints, or remove them for both.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +      description: Returns all permissions existing on the system.
This reminds me of a potential feature (perhaps you can open an issue): there could be a config option that allows users to check their own permissions. In that case the `GET` endpoints should be available to the users for any permissions that affect them.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +from typing import Dict, List
Please use tuple notation for multiple imports from the same module

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +from bson.objectid import ObjectId
I think `bson` is not a built-in module so should be grouped with `flask` in the next block

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +from werkzeug.exceptions import InternalServerError, NotFound
This should be grouped with `flask` and `bson` in the previous block.

Also, please sort each import bock alphabetically, by module name (so `foca.permission_management` _before_ `foca.utils`, although the `PERMISSION_DB_` params should end up in `current_app` anyway)

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +            "v0": rule.get("v0", None) if rule.get("v0", None) else None,
This is really really cryptic and I have no clue what's happening with these permissions. Do you have a reference where the use of `v0`, `v1` etc is explained? This is really quite problematic if we have to keep those names. I'm sure there will be a more explicit/descriptive name

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +            "v0": rule.get("v0", None) if rule.get("v0", None) else None,
Also, I don't understand the use of the ternary operator here: we set key `v0` to the value of `v0` in `rule`, if it exists, otherwise to `None`, right? But this is already achieved with this:

```python
"v0": rule.get("v0", None)
```

No need for anything that follows, I think

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +        }
So where is the `sec` property used?

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          $ref: '#/components/schemas/Rule'
Might perhaps be useful to include an optional `name` property? Possibly also for the rule?

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +        return str(permission.inserted_id)
Aren't the identifiers that MongoDB returns really unwieldy? Would perhaps be better to generate more managable identifiers. Makes that controller a lot longer, but the code be copied largely from TRS-Filer etc.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +""""Controllers for permission management endpoints."""
What's missing entirely here is the handling of `401` (should be handled automatically if you add the security definitions via `SpecConfig) and the handling of `403`.

Also, we should have a default (possibly immutable) policy in place for at least one `admin` user if `auth` is enabled.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +    return app
Add newline

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/permission_server.py
> +        raise NotFound
Add newline

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +def _register_casbin_enforcer(
See other comment ablove re: making this API less crowded

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +        },
We need to add security definitions as well!

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +def _register_permission_specs(
Don't we have a mechanism for merging YAML config files in here somewhere? If so, we could just put the config for these paths in a YAML file and merge it with/append it to the app config that the user provides. Then we could get rid of this function entirely and the user could (if they really know what they are doing) easily modify that, e.g., `config_access_control.yaml` file.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +                    # TODO: add check so user cannot enter access_db as the db name.
Yes, please implement that or create an issue and then remove this `TODO`

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +                    # TODO: add check so user cannot enter access_db as the db name.
Or actually, is there a reason why they couldn't store it in the same database (but a different collection)? So perhaps we should just give a warning if they choose to add an `access_control_db`, but only error if both the db _and_ collection name are not unique

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +            if config.db is not None:
And what if it _is_ `None`? Even if the user doesn't set up a db for the app - if they want to use our access control, we will need to tell the user to include config params for `MongoConfig`

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +                    config.db.dbs['access_db'] = DBConfig(collections=None, client=None)
`'access_db'` shouldn't be hard-coded here, I think? And why don't we assign a collection name here?

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +                    config.db.dbs = {
Do we really wanna override the databases if there are no databases (`not None`)? Shouldn't it rather be the other way around: if there are already databases, we add another one, and if there aren't we just define it?

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +    if config.access is not None:
This code is quite messy and complicated. I'm sure that can be solved more elegantly.

2021-12-14 05:26 UTC, uniqueg commented on foca/permission_management/config_utils.py
> +def _create_permission_config(
Probably we should do the same approach I suggested below: We provide a `database:` section in the `config_access_control.yaml` and then merge/append that file to the user's app config - in this way we would for sure have at least one database defined and we could just use the already existing mechanism to add this database and collection as well...

2022-01-22 18:14 UTC, kushagra189 commented on examples/petstore/config.yaml
> +access:
marking as done.

2022-01-22 18:15 UTC, kushagra189 commented on examples/petstore/docker-compose.yaml
> +    image: foca-petstore-root:latest
marking as done.

2022-01-22 18:16 UTC, kushagra189 commented on foca/database/register_mongodb.py
> -
marking as done.

2022-01-22 18:20 UTC, kushagra189 commented on foca/foca.py
> +from foca.permission_management.config_utils import _create_permission_config, _register_permission_specs, _register_casbin_enforcer
marking as done.

2022-01-22 18:21 UTC, kushagra189 commented on foca/foca.py
> +from foca.permission_management.constants import PERMISSION_DB_NAME, PERMISSION_DB_COLLECTION_NAME
marking as done.

2022-01-22 18:24 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  title: 'FOCA permission control API specification'
marking as done.

2022-01-22 18:25 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  description: 'CRUD and List Operations for managing permission.'
marking as done.

2022-01-22 18:26 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +    url: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/LICENSE'
marking as done

2022-01-22 18:27 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +    name: 'GA4GH Discovery Networks Team'
marking as done.

2022-01-22 18:30 UTC, kushagra189 commented on requirements.txt
> +flask-authz==2.4.0
marking as done.

2022-01-22 18:30 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +        raise NotFound
marking as done.

2022-01-22 18:36 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +                  $ref: '#/components/schemas/Permission'
marking as done.

2022-01-22 18:37 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        '404':
marking as done.

2022-01-22 18:39 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        '400':
marking as done.

2022-01-22 18:40 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +  - url: /admin/permission-management
marking as done.

2022-01-27 03:52 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Unique id of the permission.
resolved.

2022-01-27 03:54 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        ptype:
resolved.

2022-01-27 03:55 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Policy type.
No options, anything can be defined.

2022-01-29 07:48 UTC, kushagra189 commented on foca/models/config.py
> +class AccessConfig(FOCABaseConfig):
done.

2022-01-29 07:49 UTC, kushagra189 commented on foca/models/config.py
> +    #TODO: add check for a valid conf file
resolved.

2022-01-29 07:49 UTC, kushagra189 commented on foca/models/config.py
> +    # resolve relative path
resolved

2022-01-29 07:53 UTC, kushagra189 commented on foca/models/config.py
> +    access: Optional[AccessConfig] = None
done.

2022-01-29 12:02 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +      description: Returns all permissions existing on the system.
done.

2022-01-29 12:03 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +      parameters:
done.

2022-01-30 05:13 UTC, kushagra189 commented on examples/petstore/petstore_policies.conf
> +# Request definition
done.

2022-01-30 05:14 UTC, kushagra189 commented on foca/foca.py
> +    conf = _create_permission_config(conf)
done.

2022-01-30 05:14 UTC, kushagra189 commented on foca/foca.py
> +
done

2022-01-30 05:14 UTC, kushagra189 commented on foca/foca.py
> +    if conf.access and conf.access.enable:
done

2022-01-30 05:18 UTC, kushagra189 commented on foca/foca.py
> +    else:
done

2022-01-30 05:18 UTC, kushagra189 commented on foca/foca.py
> +    # Register permission management and casbin enforcer
done

2022-01-30 05:19 UTC, kushagra189 commented on foca/foca.py
> +            db_port=conf.db.port
done

2022-01-30 05:20 UTC, kushagra189 commented on foca/models/config.py
> +        path_out: Policy file based on `pycasbin` specification.
done

2022-01-30 05:21 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          $ref: '#/components/schemas/Rule'
Not required.

2022-01-30 05:22 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +          description: Param 5.
will explain alongside later.

2022-01-30 05:22 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +"""Methods to manage permission management configuration"""
done

2022-01-30 05:23 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +def _create_permission_config(
done

2022-01-30 05:23 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +    if config.access is not None:
fixed

2022-01-30 05:23 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +            if config.db is not None:
not needed anymore

2022-01-30 05:24 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +                    config.db.dbs = {
fixed implementation.

2022-01-30 05:25 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +                    # TODO: add check so user cannot enter access_db as the db name.
Not a problem we can use this. Creating an issue for now.

2022-01-30 05:29 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +                    config.db.dbs['access_db'] = DBConfig(collections=None, client=None)
removed.

2022-01-30 05:48 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +def _register_permission_specs(
will discuss the current implementation.

2022-01-30 05:49 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +def _register_casbin_enforcer(
Done.

2022-01-30 05:49 UTC, kushagra189 commented on foca/permission_management/config_utils.py
> +    return app
done

2022-01-30 05:50 UTC, kushagra189 commented on foca/permission_management/constants.py
> +"""File to store permission based constants
fixed as per Flake8

2022-01-30 05:51 UTC, kushagra189 commented on foca/permission_management/constants.py
> +PERMISSION_DB_NAME="access_db"
Made them configurable.

2022-01-30 05:52 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +from typing import Dict, List
Done

2022-01-30 05:53 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +from bson.objectid import ObjectId
done

2022-01-30 05:54 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +from werkzeug.exceptions import InternalServerError, NotFound
Done

2022-01-30 05:55 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +        }
Fixed

2022-02-01 16:56 UTC, kushagra189 commented on foca/models/config.py
> +
done

2022-02-01 16:57 UTC, kushagra189 commented on foca/models/config.py
> +    owner_headers: Optional[set] = {'X-User', 'X-Group'}
done

2022-02-02 11:37 UTC, kushagra189 commented on foca/permission_management/api/permission-endpoint-specs.yaml
> +        sec:
Resolved.

2022-02-02 11:38 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +""""Controllers for permission management endpoints."""
resolved.

2022-02-02 11:40 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +            "v0": rule.get("v0", None) if rule.get("v0", None) else None,
resolved

2022-02-02 11:40 UTC, kushagra189 commented on foca/permission_management/permission_server.py
> +        return str(permission.inserted_id)
need to check

2022-02-22 17:27 UTC, uniqueg requested changes
@kushagra189: the PR is too big and reviewing it I'm getting caught up in minor issues. I think we can probably leave it as is (maybe address the few comments I have made) and then refactor things later.

However, what I would really like to see before merging this is detailed documentation of how FOCA deals with access control and the petstore example. So we need a section in `README.md` that should include *detailed* instructions/explanations on:

- the FOCA access control configuration (default and how they can be customized)
- specs and controllers for access control management (default and how they can be customized)
- the policy file (petstore example and how to customize it)
- how to run the petstore app with access control enabled
- how to test that access control works as intended given the default policies (i.e., instructions on how to actually see it in action)
- how to manage access conrol given the default specs and controllers (including actual example API calls)

After reading this, a user should be able to see access control in action by deploying the petstore app localy, understand the mechanism by which FOCA enables configuring and managing access control, understand the default behavior and have enough insight to modify the defaults according to desired behavior.

2022-02-22 17:27 UTC, uniqueg commented on examples/petstore/config.yaml
> +    use_default_api_specs: True
See comment further down when model is defined.

2022-02-22 17:27 UTC, uniqueg commented on foca/models/config.py
> +        user_headers: User specific header property requirements for casbin.
Not a big fan of this design, for the following reasons:
- If not using the defaults DB config and API specs, multiple options need to be specified. This makes the class API unnecessarily complex. Would be better to, e.g., set `api_specs_path` to `None` if the default specs are to be used. Also, the behavior for setting the flags to `True` but indicating a specs path and/or a DB config is ill-defined and could cause confusion (which ones are taken?). This would not be an issue when using a single option that can be set to `None` when defaults are desired. Document this though in the arg description, but not the attribute description (the attribute should never be `None` and always be a path).
- It is unclear what the "DB config" is, just db and collection name? Also, again, using defaults is tricky here: what if the user says "True" but provides a value for `db_name` but not for `collection_name`? And what if that's actually what they want - use the default collection name but specify the db name explicitly? Again, removing the flag and allowing `db_name` and `collection_name` to be set to `None` to use defaults is more robust. However, again, document this behavior in the arg (but not attribute) description.
- Use consistent naming: `api_specs_path` vs `api_spec_controller_path` - use either `spec` or `specs`. Also, `path` does not need to be included, IMO, especially if it can take on the value of `None`. Just `api_specs` and `api_controllers` would do, IMO. And if you go with plural here, I would also change `policy_path` to `policies` (again, no `path`). See next comment for more considerations on paths.
- Consistent with Connexion, it might make sense to use `package.module` notation, rather than `/path/module` notation.
- The documentation for `owner_headers` and `user_headers` is not detailed enough - judging by the fact that I don't understand it. We are hiding complexity here, so mentioning casbin is not very helpful. Write documentation such that a user will know what to put here.

2022-02-22 17:27 UTC, uniqueg commented on examples/petstore/petstore_policies.conf
> +# Request definition
I don't see where this is done? I was thinking of more expressive/explicit/detailed descriptions, explaining what each of these statements mean

2022-02-22 17:27 UTC, uniqueg commented on examples/petstore/petstore_policies.conf
> +# Request definition
Never mind, I saw this now

2022-09-02 10:15 UTC, uniqueg approved these changes

2022-09-02 17:36 UTC, merged

2022-09-02 22:21 UTC, uniqueg commented
🚀