Fix: Rethink storage of modified specs
elixir-cloud-aai/foca pull request #196
Opened 2023-12-15 15:20 UTC by Rahuljagwani

## Description

Fixes #158

I just tried directly passing `spec_parsed` instead of writing it in a file.

Two test cases failed which were:

```
    def test_register_openapi_spec_cannot_serialize(self):
        """Registration failing because modified specs cannot be serialized."""
        app = App(__name__)
        spec_configs = [SpecConfig(
            path=PATH_SPECS_2_YAML_ORIGINAL,
            path_out=PATH_SPECS_2_YAML_MODIFIED,
            add_operation_fields=OPERATION_FIELDS_2_NO_RESOLVE,
        )]
        with pytest.raises(YAMLError):
            register_openapi(app=app, specs=spec_configs)

    def test_register_openapi_spec_cannot_write(self):
        """Registration failing because modified specs cannot be written."""
        app = App(__name__)
        spec_configs = [SpecConfig(
            path=PATH_SPECS_2_YAML_ORIGINAL,
            path_out=PATH_NOT_FOUND,
        )]
        with pytest.raises(OSError):
            register_openapi(app=app, specs=spec_configs)
```

These cases are about `modified_specs` but since directly passing the dictionary does not allow the creation of a new `.yaml` file. I think these might not be of the best use.

This will solve the deployment problem also mentioned in #158 as there is no need to create a file with write permissions.
I have also pushed the code that was being discussed in #158 in the branch name `modified_specs_storage`. I will be making a PR from that also so that a better one can be merged.

Please let me know if I am wrong or if I missed something :)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have updated the documentation (or documentation does not need to be updated)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have not reduced the existing code coverage

2023-12-16 15:37 UTC, uniqueg requested changes
Awesome! If this really works like that (and I suppose it does if the petstore integration tests pass), I definitely intend to merge it once you removed the commented code. It avoids the need to write stuff _and_ gets rid of some code - what more could we ask for? :)

So no need to work on the other solution we discussed. This should be much better.

2023-12-16 15:37 UTC, uniqueg commented on foca/api/register_openapi.py
> +# import yaml
Please just delete any lines you don't need anymore. Everything is version controlled, so there is no need to keep unused code - if we need to revert or reuse unused code later on, we can always go back.

2023-12-16 15:37 UTC, uniqueg commented on foca/api/register_openapi.py
> +        # logger.debug(f"Wrote specs to file: {spec.path_out}")
As above.

2023-12-16 15:37 UTC, uniqueg commented on tests/api/test_register_openapi.py
> +    #         register_openapi(app=app, specs=spec_configs)
As above.

2023-12-16 18:26 UTC, Rahuljagwani commented
Sure, I will be removing the comments. Just one more thing, I emailed you asking about the onboarding instructions(My email- rahuljagwani1012@gmail.com). I have not received a reply on that yet. Please look into it :)

2023-12-17 11:28 UTC, uniqueg approved these changes

2023-12-17 11:28 UTC, merged