Upgraded pymongo version to 4.7.2
elixir-cloud-aai/foca pull request #213
Opened 2024-05-13 22:59 UTC by athith-g

## Description

Fixes #212.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [x] I have performed a self-review of my own code
- N/A I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation (or documentation does not need to be updated)
- [x] My changes generate no new warnings
- N/A I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage

2024-05-13 23:01 UTC, athith-g commented on examples/petstore-access-control/docker-compose.yaml
I assumed the db port in petstore-access-control differs from the db port for petstore in order to be able to run both simultaneously. If this is the case, should I also change the port for the app container?

2024-05-14 14:23 UTC, uniqueg commented on examples/petstore-access-control/docker-compose.yaml
That's not a bad idea. However, they may always be port conflicts for any given user, regardless of what ports we use. In any case, it's a different issue and nobody requested it, so let's leave the ports as they were here (i.e., please roll back `12345` to `27017`).

2024-05-14 14:32 UTC, uniqueg commented on examples/petstore-access-control/docker-compose.yaml
On another note: I think it would make sense to also upgrade MongoDB to the latest version in the `docker-compose.yml` files for the two example apps in this PR.

2024-05-14 14:34 UTC, uniqueg requested changes
Please have a look at the open thread. Also, I'm concerned about the failing tests. They are not your fault, but I can't publish a release before these are fixed. So that will delay things. Try not to get blocked by this by using your local FOCA branch that has this issue fixed.

2024-05-14 14:49 UTC, athith-g commented on examples/petstore-access-control/docker-compose.yaml
Ah that makes sense I'll get to changing those thanks. The reason I changed the port was because the db port is 12345 in the [mock data](https://github.com/elixir-cloud-aai/foca/blob/dev/tests/mock_data.py#L18) that is used by the [access control tests](https://github.com/elixir-cloud-aai/foca/blob/dev/tests/security/access_control/test_register_access_control.py#L18). Should I change the port in the mock data to 27017 instead?

2024-05-19 22:18 UTC, uniqueg commented on examples/petstore-access-control/docker-compose.yaml
Sorry, I didn't see your reply. I think what's in the mock data _shouldn't_ matter, it's just a different config, any port should work. But let's keep the more standard `27017` port for the petstore apps. More generally, let's only change what's necessary in any given PR :)

Speaking of which, I didn't quite understand which unit tests failed because of the port in #214. I will comment there.

2024-05-20 00:25 UTC, uniqueg commented
Closing in favor of #220 which builds on this PR

2024-05-20 00:25 UTC, closed without merging