Fixes docstrings and sets private members
elixir-cloud-aai/foca pull request #96
Opened 2021-02-21 20:13 UTC by kushagra189

## Description

Google type docstrings were improper and did not adhere to the required format. Fixed them as per the standards mentioned under the official guidelines. For reference check:
* [Sphinx napolean google docstring example](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)
* [Official sphinx docs](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html)

Fixes #70 

## Type of change

Please delete options that are not relevant.

- [x] Documentation update

## Checklist:

- [x] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage

2021-02-24 10:10 UTC, uniqueg requested changes
I'm really sorry, but I think there's been quite some misunderstanding. Most of the changes you made are going in the wrong direction. The main point of the issue was to check the API docs on Read the Docs, find instances where the docstrings don't render well and try to fix those. In most cases this would probably mean to use the correct reStructuredText formatting, especially with a view to their use in Python docs (see here: https://www.python.org/dev/peps/pep-0287/#docstring-significant-features). A minor point was to check the consistency of the docstrings with the general recommendations (https://www.python.org/dev/peps/pep-0257/) and Google style (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), but in cases of ambiguity or multiple choices (see individual comments on class level vs class constructor docstrings, skipping explicit type annotations and defaults) keep the one that is most prevalent in our docs (because I _did_ already think quite hard about which one to pick and might just not have caught every single instance for each when doing reviews).

I know this is annoying work, and in this particular case it will probably mean to go back and start a new PR entirely, so I understand if you'd rather not do it. Please let me know. And again, I'm really sorry for the misunderstanding, I should have caught earlier that this wasn't really going in the right direction (or perhaps the right direction, but way ahead).

2021-02-24 10:10 UTC, uniqueg commented on foca/api/register_openapi.py
> +        app (App): A Connexion app instance.
I'm really sorry to nag again about this PR (and probably should have seen this before), but since we are doing type hints (and those translate nicely to the API docs currently), we should _not_ explicitly annotate parameter and return types in the docstrings again. The reason (apart from additional work) is that this is almost certainly going to lead to diverging _actual_ type annotations and those mentioned in the docstrings, because comments are frequently not updated when the code is. The actual code base (and Python type hints can be considered part of that) should be the authoritative truth whenever possible, to avoid just the problem of code and comments diverging. Using _only_ type hints is therefore MUCH better in this case. You can compare the second example [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) to see that this is fully within the Google docstring scope.

2021-02-24 10:10 UTC, uniqueg commented on foca/api/register_openapi.py
> +    Returns:
The Google style docstring examples or description [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) and [here](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings) do not mention that sections like `Raises` and `Returns` should be arranged alphabetically. Rather, the order typically seems to be:

- Summary line (should fit on one line)
- Extended description
- `Notes`
- `Args` (followed by `Attributes`, if applicable)
- `Returns`
- `Raises`
- `Examples`

2021-02-24 10:10 UTC, uniqueg commented on foca/api/register_openapi.py
> -    Register OpenAPI specs with Connexion app.
Given that Connexion is also a package name, one could perhaps use `connexion` in single backticks as is described [here](https://www.python.org/dev/peps/pep-0287/#docstring-significant-features) for any Python identifiers (see third bullet point).

2021-02-24 10:10 UTC, uniqueg commented on foca/api/register_openapi.py
> +        App: A Connexion app instance.
Again: please *no* type annotations in docstrings

2021-02-24 10:10 UTC, uniqueg commented on foca/config/config_parser.py
> +                format. Defaults to None.
Defaults are also obvious from the function definitions and thus should be omitted. Diverging comments and code base are an even bigger problem here, as defaults are changed relatively frequently and users might end up assuming (and reporting) wrong usage parameters

2021-02-24 10:10 UTC, uniqueg commented on foca/config/config_parser.py
> +        """Initialiser method for `ConfigParser` class.
The [Google docstring examples](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) have this to say about classes and class constructors:

```
    The __init__ method may be documented in either the class level
    docstring, or as a docstring on the __init__ method itself.

    Either form is acceptable, but the two should not be mixed. Choose one
    convention to document the __init__ method and be consistent with it.
```

Of course it is a matter of taste and the most important point is consistency. But since, e.g., the Pydantic model classes do not have constructors, I deliberately followed the style where class constructors are documented in the class itself to improve consistency. This also puts `Args` and `Attributes` (which are often the same) together, which may make it more likely that both are updated consistenly during future refactoring. The constructor docstrings can thus be recuded to a minimum (just the summary line as it was before) or even omitted.

2021-02-24 10:10 UTC, uniqueg commented on foca/config/config_parser.py
> +        Note:
I think this is rather an extended description. I think `Note` sections should be used to draw attention to specific dangers/gotchas etc.

2021-02-24 10:10 UTC, uniqueg commented on foca/config/config_parser.py
> +        """Initialiser method for `ConfigParser` class.
I also think that including the class name is again an issue that may lead to comments and code base diverging. I don't think the information is very helpful either, as the docs will always make it obvious which class a method is in.

2021-02-24 10:10 UTC, uniqueg commented on foca/config/config_parser.py
> +            Optional[Dict]: Dictionary of merged YAML file contents, or None
Now, the main point of this issue (apart from ensuring consistency) was to change those parts of the docstrings that don't render well on the auto-created API docs. I assume that `None` in backticks might have been one such case. However, I strongly believe that having `None`, `True` and `False` stand out graphically is important to understand that they have a special meaning and aren't just the English words. If single backticks are inappropriate here (they may be) and don't render well, perhaps try double backticks (as mentioned [here](https://www.python.org/dev/peps/pep-0287/#docstring-significant-features)) for inline literals are the right choice here.

2021-02-24 10:10 UTC, uniqueg commented on foca/database/register_mongodb.py
> +        ``config['database']['database']`` contains the database object;
Good!

2021-02-24 10:10 UTC, uniqueg commented on foca/database/register_mongodb.py
> +        Optionally, basic authorization can be set by environment variables.
Perhaps not really part of this issue, but how? :)

2021-02-24 10:10 UTC, uniqueg commented on foca/errors/exceptions.py
> +        format (str, optional): One of 'oneline' (default), 'minimal', or
All literals probably should have double backticks surrounding them

2021-02-24 10:10 UTC, uniqueg commented on foca/foca.py
> +            :py:class:`foca.models.config.Config()`. Defaults to None.
Does the use of the `:` to define the Python identifier type (according to [this document](https://www.python.org/dev/peps/pep-0287/#docstring-significant-features), fourth bullet point) lead to improved rendering? Specifically, does it create a link to that model? If not, I think we can omit it. Otherwise I think we should use wherever we are referring to a Python identifier

2021-02-24 10:10 UTC, uniqueg commented on foca/foca.py
> +            :py:class:`foca.models.config.Config()`. Defaults to None.
It actually seems to do so _with_ the type definition, but not sure it will also do it without. I'm wondering because the behavior is mixed: some (perhaps all?) references to FOCA modules/classes are linked on the API docs, but if, in a description of a parameter of a function or method, we are referring to another parameter in that same method, there is no link created. Ideally, of course, all such instances should be cross-linked, with the exception perhaps of members in external Python modules (guess that would be too much to ask from Read the Docs, although I think VS Code with the Python extension indeed does that)

2021-02-24 10:10 UTC, uniqueg commented on foca/security/auth.py
> +        Unauthorized: Raised if JWT could not be successfully validated.
`Unauthorized` is not a standard Python error, and I think it's important that we indicate what error is raised specifically.

2021-03-15 04:29 UTC, closed without merging

2021-03-15 04:30 UTC, kushagra189 commented
Deleting this PR and the branch since the changes were not in line with the required flow.